### ISSUE TITLE
healthcareservice example is not recognized

### ISSUE THREAD

**Issue by Healthedata1** [HL7/VhDir#2]
10/29/2018 build notes:

HealthCareService examples not working 

fixed example to pass latest R4 schema
updated ig-publisher

commented out `eligibility`  as workaround

~~~
Stack Dump (for debugging):                                                      (38.0855sec)
java.lang.Exception: Unable to determine type for  /Users/ehaas/Documents/FHIR/VhDir/source/examples/healthcareservice-example-independencerehab1: com.google.gson.JsonArray cannot be cast to com.google.gson.JsonObject
	at org.hl7.fhir.igtools.publisher.Publisher.loadAsElementModel(Publisher.java:2394)
	at org.hl7.fhir.igtools.publisher.Publisher.load(Publisher.java:1778)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:582)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:526)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:4925)
Caused by: java.lang.ClassCastException: com.google.gson.JsonArray cannot be cast to com.google.gson.JsonObject
	at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:182)
	at org.hl7.fhir.r4.formats.JsonParser.parseHealthcareServiceProperties(JsonParser.java:13100)
	at org.hl7.fhir.r4.formats.JsonParser.parseHealthcareService(JsonParser.java:13025)
	at org.hl7.fhir.r4.formats.JsonParser.parseResource(JsonParser.java:27544)
	at org.hl7.fhir.r4.formats.JsonParserBase.parse(JsonParserBase.java:92)
	at org.hl7.fhir.r4.formats.ParserBase.parse(ParserBase.java:58)
	at org.hl7.fhir.r4.elementmodel.ObjectConverter.convert(ObjectConverter.java:90)
	at org.hl7.fhir.igtools.publisher.Publisher.loadAsElementModel(Publisher.java:2387)
	... 4 more
Exception in thread "main" java.lang.NullPointerException
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:4935)
~~~

**Comment by Healthedata1** [comment]
Uncomment element when fixed
